# Site settings
title: Murilo Mothsin
email: murilo.mothsin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles about software development, developer's daily routines and all shiny new tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://murilomothsin.github.io/" # the base hostname & protocol for your site
twitter_username: Murilo_Mothsin
github_username:  murilomothsin

# Build settings
markdown: kramdown
